//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.308
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace MvcContrib.ObjectBuilder.Configuration
{
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="container-config")]
    [XmlRoot("ContainerConfig", Namespace="container-config", IsNullable=false)]
    public partial class ContainerXmlConfigElement
    {
        private MappingElement[] mappingsField;

        private BuildRuleElement[] buildRulesField;

        private bool enableReflectionField;

        public ContainerXmlConfigElement()
        {
            enableReflectionField = true;
        }

        /// <remarks/>
        [XmlArrayItem("Mapping", IsNullable=false)]
        public MappingElement[] Mappings
        {
            get { return mappingsField; }
            set { mappingsField = value; }
        }

        /// <remarks/>
        [XmlArrayItem("BuildRule", IsNullable=false)]
        public BuildRuleElement[] BuildRules
        {
            get { return buildRulesField; }
            set { buildRulesField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        [DefaultValue(true)]
        public bool EnableReflection
        {
            get { return enableReflectionField; }
            set { enableReflectionField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="container-config")]
    public partial class MappingElement
    {
        private string fromTypeField;

        private string toTypeField;

        /// <remarks/>
        [XmlAttribute()]
        public string FromType
        {
            get { return fromTypeField; }
            set { fromTypeField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string ToType
        {
            get { return toTypeField; }
            set { toTypeField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="container-config")]
    public partial class MethodElement
    {
        private object[] itemsField;

        private string nameField;

        /// <remarks/>
        [XmlElement("Ref", typeof(RefElement))]
        [XmlElement("Value", typeof(ValueElement))]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="container-config")]
    public partial class RefElement
    {
        private string typeField;

        /// <remarks/>
        [XmlAttribute()]
        public string Type
        {
            get { return typeField; }
            set { typeField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="container-config")]
    public partial class ValueElement
    {
        private string typeField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public string Type
        {
            get { return typeField; }
            set { typeField = value; }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get { return valueField; }
            set { valueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="container-config")]
    public partial class PropertyElement
    {
        private object itemField;

        private string nameField;

        /// <remarks/>
        [XmlElement("Ref", typeof(RefElement))]
        [XmlElement("Value", typeof(ValueElement))]
        public object Item
        {
            get { return itemField; }
            set { itemField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="container-config")]
    public partial class ConstructorElement
    {
        private object[] itemsField;

        /// <remarks/>
        [XmlElement("Ref", typeof(RefElement))]
        [XmlElement("Value", typeof(ValueElement))]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="container-config")]
    public partial class BuildRuleElement
    {
        private ConstructorElement constructorField;

        private PropertyElement[] propertyField;

        private MethodElement[] methodField;

        private string typeField;

        private ModeElement modeField;

        /// <remarks/>
        public ConstructorElement Constructor
        {
            get { return constructorField; }
            set { constructorField = value; }
        }

        /// <remarks/>
        [XmlElement("Property")]
        public PropertyElement[] Property
        {
            get { return propertyField; }
            set { propertyField = value; }
        }

        /// <remarks/>
        [XmlElement("Method")]
        public MethodElement[] Method
        {
            get { return methodField; }
            set { methodField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Type
        {
            get { return typeField; }
            set { typeField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public ModeElement Mode
        {
            get { return modeField; }
            set { modeField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable()]
    [XmlType(Namespace="container-config")]
    public enum ModeElement
    {
        /// <remarks/>
        Singleton,

        /// <remarks/>
        Instance,
    }
}