using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("0.0.1.157")]
[assembly: AssemblyFileVersionAttribute("0.0.1.157")]
[assembly: AssemblyCopyrightAttribute("Copyright © MVC Contrib 2007-2008")]
[assembly: AssemblyProductAttribute("MVCContrib")]
[assembly: AssemblyCompanyAttribute("MVC Contrib")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("0.0.1.157")]

