<%@ Page Language="C#" MasterPageFile="~/Views/Shared/Layout.master" Inherits="System.Web.Mvc.ViewPage" %>
<%@ Import Namespace="MvcContrib.Samples.FormHelper.Models" %>
<asp:Content ContentPlaceHolderID="body" runat="server">
	<p>
		FormHelper currently supports generating the following HTML elements:
		<ul>
			<li>Text fields</li>
			<li>Text areas</li>
			<li>Hidden fields</li>
			<li>Checkbox fields</li>
			<li>Dropdown lists &amp; listboxes</li>
			<li>Radio fields</li>
			<li>Checkbox Lists</li>
			<li>Radio Lists</li>
			<li>Submit buttons</li>		
			<li>Form tags</li>	
			<li>Validators</li>
		</ul>
		<p>
			Most of the helpers have three overloads - the simplest takes the element's name. The second can take an IDictionary of HTML attributes and the third takes a strongly typed object for the HTML attributes.
		</p>
	</p>
	<h1>Text Fields</h1>
	<p>
		The name given to the text box is used for databinding. This example automatically extracts the "Name" property from the "person" object in the ViewData:<br />
		<%= Html.FormHelper().TextField("person.Name") %><br /><br />
		HTML attributes can be specified using a dictionary or a strongly typed object:<br />
		Using a dictionary: <%= Html.FormHelper().TextField("person.Name", new Hash(@class => "demo1")) %><br />
		Using strongly typed options: <%= Html.FormHelper().TextField(new MvcContrib.UI.Tags.TextBox { Name = "person.Name", Class = "demo1" }) %>
		<br />
		<p>The same applies to text areas:</p>
		<%= Html.FormHelper().TextArea("person.Name", new Hash(rows => 10, cols => 40)) %>
	</p>
	<h1>Hidden fields</h1>
	<p>Hidden fields can be created using a similar syntax (view source to see generated HTML):</p>
	<%= Html.FormHelper().HiddenField("person.Id") %>
	<h1>Checkbox fields</h1>
	<p>Note that for checkbox fields, a hidden field is also generated with the same name to allow for easier databinding.</p>
	<p>Is user a developer? <%= Html.FormHelper().CheckBoxField("person.IsDeveloper") %></p>
	<h1>Radio Buttons</h1>
	<p>
		Radio buttons can be created using a similar syntax to checkboxes. With radio buttons, the value must be specified as the second parameter:<br /><br />
		<%= Html.FormHelper().RadioField("person.IsDeveloper", true, new Hash(label => "User is a developer")) %><br />
		<%= Html.FormHelper().RadioField("person.IsDeveloper", false, new Hash(label => "User is not a developer")) %>
		
	</p>	
	
	<h1>Dropdown (select)</h1>
	<p>
		A dropdown takes an enumerable object as its DataSource parameter. The TextField and ValueField properties are used for databinding: <br />
		<%= Html.FormHelper().Select("person.RoleId", ViewData["roles"], "Name", "Id", new Hash(firstOption => "Please select...")) %>
	</p>
	<p>The options can also be strongly typed.</p>
	<p>It is also possible to use an Enum as the datasource for a Select by using a generic overload:</p>	
	<p>
		<%= Html.FormHelper().Select<Gender>("person.Gender") %>
	</p>
	
	<h1>Listbox (select)</h1>
	<p>
		A listbox can also be created using the Select method by setting the 'Size' property to a value greater than 1. Multiple selected values are also supported.<br />
		<%= Html.FormHelper().Select("listbox1", ViewData["roles"], "Name", "Id", new Hash(size => 5, multiple => true, selectedValue => new[] { 1, 2 } )) %>
	</p>
	
	<h1>Checkbox Lists and Radio Lists</h1>
	<p>Checkbox lists and radio lists can be generated in one of three ways. The standard method outputs a horizontal list:</p>
	<%= Html.FormHelper().CheckBoxList("accessLevel", ViewData["roles"], "Name", "Id") %>
	<p>You can use the ToFormattedString method to create a vertical list:</p>
	<%= Html.FormHelper().CheckBoxList("accessLevel2", ViewData["roles"], "Name", "Id").ToFormattedString("{0}<br />") %>
	<p>You can also iterate over the checkbox list to manually manipulate each checkbox/radio button</p>
	<% foreach(var checkbox in Html.FormHelper().CheckBoxList("accessLevel3", ViewData["roles"], "Name", "Id")) { %>
		<% if(checkbox.Value.Equals("2")) { checkbox.Checked = true; }%>	
		<%= checkbox %>
	<% } %>	
	
	<h1>Form Tags</h1>
	<p>Form tags can be generated by calling <b>Form.For</b>. Note: this syntax is currently only available when using C# in conjunction with the WebForms view engine.</p>
	<% Html.FormHelper().For<Person>((Person)ViewData["person"], "/home.mvc/FormHelper", form =>
    { %>
		<% form.Attributes.Add("class", "foo"); %>
		Name: <%= form.TextField("Name") %><br />
		Is Developer?: <%= form.CheckBoxField("IsDeveloper") %><br /><br />
		<%= form.Submit() %>
	<%}); %>
</asp:Content>
